name: Release Artifacts

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run build
      - name: Upload artifacts to workflow run
        uses: actions/upload-artifact@v4
        with:
          name: spoolman-dwc-0.5.0
          path: dist/*
      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/Spoolman-0.5.0.zip
            dist/spoolman-bridge-server-0.5.0.zip
